# Generated by Django 3.2.18 on 2023-04-05 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=25)),
                ('yosh', models.IntegerField()),
                ('ish_vaqti', models.IntegerField()),
                ('user_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Haydovchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=25)),
                ('tel', models.CharField(max_length=13)),
                ('kiritilgan_sana', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Suv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brend', models.CharField(max_length=50)),
                ('narx', models.IntegerField()),
                ('litr', models.IntegerField()),
                ('batafsil', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Mijoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=25)),
                ('tel', models.CharField(max_length=13)),
                ('manzil', models.CharField(max_length=200)),
                ('qarz', models.IntegerField()),
                ('user_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Buyurtma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyurtma_vaqti', models.DateTimeField()),
                ('miqdor', models.CharField(max_length=25)),
                ('umumiy_narx', models.IntegerField()),
                ('admin_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.admin')),
                ('haydovchi_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.haydovchi')),
                ('mijoz_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.mijoz')),
                ('suv_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.suv')),
            ],
        ),
    ]
